token:
  expiration_time: 86400000
  secret: my-very-very-secret-key-1234567890abcd_prod

gateway:
  ip: 172.31.96.1

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: "{cipher}955f8bd72a3d2d5ac187a77e06ba4fd20dcd3bb62820519fb4c81ca12dbb1f66"

gateway:
  ip: 172.18.0.5

order_service:
  url: http://order-service/order-service/%s/orders
  #앞에 order-service는 application이름
  exception:
    orders_is_empty: User's orders is Empty.
